/**
 * Generated by scripts/gen-cordis-inspect-catalog.ts — do not edit by hand; run
 * `pnpm run gen-cordis-inspect-catalog` to regenerate (freshness-gated by
 * `pnpm run verify-cordis-inspect-catalog` in doc-sync).
 *
 * The machine-readable cordis API catalog `cordis_inspect` serves to the
 * model: harness services (summary + structured public method contracts),
 * harness events (mode + structured listener contracts), and the inherited `ctx` API. Produced by
 * the same AST walk as docs/cordis-catalog, so this data and the rendered
 * docs cannot diverge.
 *
 * @module @deepseek-ai/dsh-cordis-client-runner/client/api-catalog
 */

/* jscpd:ignore-start */
/** One named parameter in a Service method or Event listener. */
export interface ApiParameter {
  /** Parameter name from the exact signature. */
  name: string
  /** Source-owned parameter contract. */
  description: string
}

/** One public service member and its source-owned contract. */
export interface ServiceApiMethod {
  /** Public method signature with its body stripped. */
  signature: string
  /** Method purpose and behavior. */
  description: string
  /** Named parameters in signature order. */
  parameters: readonly ApiParameter[]
  /** Non-void result contract when documented. */
  returns?: string
  /** Documented failure conditions. */
  throws?: readonly string[]
}

/** One harness `ctx.<key>` service and its public methods. */
export interface ServiceApiEntry {
  /** The `ctx.<key>` name, e.g. `tools`. */
  key: string
  /** First sentence of the service class JSDoc. */
  summary: string
  /** Complete service description. */
  description: string
  /** Public methods, bodies stripped, in source order. */
  methods: readonly ServiceApiMethod[]
}

/** One harness event: its dispatch mode, exact signature, and listener contract. */
export interface EventApiEntry {
  /** The scoped event name, e.g. `agent/status`. */
  name: string
  /** The dispatch mode from the declaration's `@mode` tag. */
  mode: string
  /** The exact listener signature, whitespace-normalized. */
  signature: string
  /** First sentence of the event JSDoc. */
  summary: string
  /** Complete event description. */
  description: string
  /** Named listener parameters in signature order. */
  parameters: readonly ApiParameter[]
}

/** One inherited (cordis core + loader/hmr/timer) `ctx` member group with its summary. */
export interface InheritedApiEntry {
  /** The `ctx` member name(s), e.g. `ctx.on / ctx.once`. */
  name: string
  /** One-line summary of what the member does. */
  summary: string
}

/** One named type declaration referenced by a Service or Event signature. */
export interface TypeApiEntry {
  /** The exported type/interface name, e.g. `ShellRunResult`. */
  name: string
  /** The full declaration text, comments stripped. */
  declaration: string
}

/** Every harness `ctx.<key>` service, sorted by key. */
export const SERVICE_API: readonly ServiceApiEntry[] = [
  {
    key: 'layout',
    summary: 'Panel navigation and geometry actions exposed through ctx.layout.',
    description: 'Panel navigation and geometry actions exposed through ctx.layout.',
    methods: [
      {
        signature: 'selectPanel(panelId: MainPanelId | null): void',
        description: 'Select a global central panel without changing the current Session.',
        parameters: [{ name: 'panelId', description: 'registered main key, or null to show the Conversation.' }],
        throws: ['if the selected main key is not registered; preserves the current selection.'],
      },
      {
        signature: 'beginNavigation(): AbortSignal',
        description: 'Start an asynchronous navigation, superseding any earlier pending navigation.',
        parameters: [],
        returns: 'a signal aborted by the next navigation or layout disposal; check it before committing UI state.',
      },
      {
        signature: 'toggleSidebar(): void',
        description: 'Toggle the sidebar panel (closed ⟷ contract default width).',
        parameters: [],
      },
      {
        signature: 'openRightbar(track: boolean, fullscreen: boolean): void',
        description: 'Report the right panel\'s presentation without changing its expanded state.',
        parameters: [{ name: 'track', description: 'whether the normal panel width reserves a grid track, including beneath a fullscreen overlay.' }, { name: 'fullscreen', description: 'whether the panel covers the frame and hides its outer resize handle; independent of the underlying grid track.' }],
      },
      {
        signature: 'closeRightbar(): void',
        description: 'Report the right panel as hidden: no track, no handle.',
        parameters: [],
      },
    ],
  },
  {
    key: 'locale',
    summary: 'Dictionary registry plus locale preference.',
    description: 'Dictionary registry plus locale preference. Lookup walks the active language\'s declared fallback chain in the entry namespace, then repeats it in the shared common namespace before showing the key itself. Reads go through getLocale; preferences change only through setLocale, while language packs extend the catalog through addLanguage. Continuous sync uses the `locale/change` event or the LocaleFace getSnapshot/subscribe pair installed through `ctx.slots.installLocale`.',
    methods: [
      {
        signature: 'getLocale(): LocaleSnapshot',
        description: 'Read the current immutable locale snapshot.',
        parameters: [],
        returns: 'the current snapshot (stable reference until the next change).',
      },
      {
        signature: 'getSnapshot(): LocaleSnapshot',
        description: 'LocaleFace getSnapshot: the current snapshot (carries `revision`; stable reference between changes, uSES-safe).',
        parameters: [],
        returns: 'the current snapshot.',
      },
      {
        signature: 'subscribe(fn: () => void): () => void',
        description: 'LocaleFace subscribe: notified on every snapshot change (locale switch or dictionary registration — registrations bump the revision so already rendered outlets pick up late-arriving dictionaries and locale definitions).',
        parameters: [{ name: 'fn', description: 'change callback.' }],
        returns: 'unsubscribe.',
      },
      {
        signature: 'setLocale(id: string): void',
        description: 'Switch the active locale — the only user preference write entry.\n\nThe durable write happens even when the id already matches the active locale, because the active value may be a provisional browser-derived or fallback resolution that nothing has stored yet. Picking the language already on screen is still an explicit choice, and it must survive a different browser sharing the same DSH home. Only the render notification is conditional: republishing an unchanged locale would churn every subscriber for nothing.',
        parameters: [{ name: 'id', description: 'a registered locale id; unknown ids throw.' }],
      },
      {
        signature: 'addLanguage(input: LanguageRegistration): () => void',
        description: 'Add one selectable language to the shared catalog. Its fallback must already be registered, and following fallback definitions must terminate at English. Dictionaries may register before or after this definition. Registration rechecks an unresolved Host preference and the browser\'s ordered language list. The caller owns the returned disposer; removing an active language falls back without clearing the stored id.',
        parameters: [{ name: 'input', description: 'stable id, self-described label, and fallback language id.' }],
        returns: 'idempotent disposer removing this exact definition.',
        throws: ['when fields are malformed, the id is occupied, or the fallback target is unknown or creates a cycle.'],
      },
      {
        signature: 'register<N extends Extract<keyof LocaleNamespaceMap, string>>(ns: N, dicts: Record<BuiltInLocaleId, LocaleDictOf<N>>): () => void',
        description: 'Register a declared namespace\'s dictionaries, all locales in one call — the typed form: each dictionary is checked against the namespace\'s LocaleNamespaceMap key union (a missing or extra key is a compile error), and every shipped locale is required (bilingual balance enforced at registration). Duplicate (ns, locale) throws (single occupant; a namespace\'s texts have one owner). Registration bumps the revision so mounted outlets pick up late-arriving dictionaries.',
        parameters: [{ name: 'ns', description: 'a namespace merged into LocaleNamespaceMap.' }, { name: 'dicts', description: 'complete dictionaries keyed by built-in locale id.' }],
        returns: 'disposer removing every locale registered by this call (idempotent).',
      },
      {
        signature: 'register(ns: string, locale: string, dict: LocaleDict): () => void',
        description: 'Single-locale untyped form for language-pack contributions and namespaces outside the merge table.',
        parameters: [{ name: 'ns', description: 'namespace.' }, { name: 'locale', description: 'locale tag.' }, { name: 'dict', description: 'dictionary.' }],
        returns: 'disposer (idempotent).',
        throws: ['when locale is not a BCP 47-style tag.'],
      },
      {
        signature: 'bind<N extends Extract<keyof LocaleNamespaceMap, string>>(ns: N): TranslateNS<N>',
        description: 'Bind a declared namespace to a translate function typed to its dictionary key union (plus the shared common vocabulary) — the same key domain the framework-injected `t` seat carries. The returned reference is stable per namespace (repeat binds return the same function), so it can ride inject surfaces without breaking memoization.',
        parameters: [{ name: 'ns', description: 'a namespace merged into LocaleNamespaceMap.' }],
        returns: 'the typed translate function (reads the active locale at call time).',
      },
      {
        signature: 'bind(ns: string): Translate',
        description: 'Untyped form for namespaces outside the merge table (dynamic composition, tests).',
        parameters: [{ name: 'ns', description: 'namespace.' }],
        returns: 'the translate function.',
      },
    ],
  },
  {
    key: 'sessions',
    summary: 'The sessions-service face injected as `ctx.sessions`.',
    description: 'The sessions-service face injected as `ctx.sessions`.',
    methods: [
      {
        signature: 'open(id: SessionId): void',
        description: 'Select a session as current.',
        parameters: [{ name: 'id', description: 'session id (must exist in the list; unknown ids fail loud).' }],
      },
      {
        signature: 'openSubagent(address: SubagentAddress): void',
        description: 'Open a healthy catalog child through its exact direct-parent address.',
        parameters: [{ name: 'address', description: 'catalog-derived parent and child ids.' }],
      },
      {
        signature: 'setSubagentCatalogOpen(parentSessionId: SessionId, open: boolean): void',
        description: 'Mark whether a catalog menu is consuming live membership updates.',
        parameters: [{ name: 'parentSessionId', description: 'catalog owner.' }, { name: 'open', description: 'current menu state.' }],
      },
      {
        signature: 'refreshSubagents(parentSessionId: SessionId): Promise<void>',
        description: 'Refresh one direct-child catalog.',
        parameters: [{ name: 'parentSessionId', description: 'catalog owner.' }],
        returns: 'completion of the current or newly started refresh.',
      },
      {
        signature: 'search( query: string, signal: AbortSignal, ): Promise<RemoteResult<{ items: SessionSearchResultItem[]; hasMore: boolean }>>',
        description: 'Search the Host\'s visible message-content index. Results stay request-local; the list snapshot remains the metadata authority.',
        parameters: [{ name: 'query', description: 'non-blank literal phrase.' }, { name: 'signal', description: 'cancellation for a superseded search.' }],
        returns: 'bounded results, or a business/transport error.',
      },
      {
        signature: 'fork(opts: { sessionId: SessionId; atSeq?: number; increaseTitle?: boolean }): Promise<SessionId>',
        description: 'Fork a session from a completed-turn prefix of the source; on resolution the child is in the list store and `open()` can target it.',
        parameters: [{ name: 'opts', description: 'source session id, the optional event seq anchoring the cut (the boundary is the first turn/end at or after it; an in-log anchor in an open turn is unavailable rather than clipped backward), and whether to increment an inherited durable title before resolving.' }],
        returns: 'the child session id.',
        throws: ['when the fork fails, or when a requested child-title rename fails after creation.'],
      },
      {
        signature: 'scope(id: SessionId): AgentContext | undefined',
        description: 'Resolve an Agent-scoped context view (use-and-discard).',
        parameters: [{ name: 'id', description: 'session id.' }],
        returns: 'scoped ctx, or undefined for a session neither listed nor already scoped.',
      },
      {
        signature: 'binding(id: SessionId): SessionBinding | undefined',
        description: 'Resolve the stable session binding (scope-addressed assembly feed).',
        parameters: [{ name: 'id', description: 'session id.' }],
        returns: 'binding, or undefined for a session neither listed nor already scoped.',
      },
    ],
  },
  {
    key: 'slots',
    summary: 'cordis Service layer of the slot system; see the module doc for the split with SlotCore.',
    description: 'cordis Service layer of the slot system; see the module doc for the split with SlotCore.',
    methods: [
      {
        signature: 'declare readonly register: SlotCore[\'register\']',
        description: 'The single registration API. The typed face IS the core\'s register (both overloads reused verbatim — one authority, no structural copy; see SlotCore.register for children declaration, store seat, inject face, load-time validation, and the unload cascade). This layer adds: disposal through the caller\'s ctx.effect (fiber unload = cascade), exclusive-factory minting (`store: createXxxStore` becomes a per-entry handle), the registrant diagnostics stamp, and store-instance lifecycle on the entry axis.\n\nDeclared here, implemented by prototype assignment below the class: it MUST stay a prototype method (never an instance arrow) — the cordis service proxy binds `this.ctx` to the CALLER\'s context at call time, which is what routes the effect (and the unload cascade) into the caller\'s fiber. An arrow property would freeze `this` to the service\'s own root ctx and silently break per-plugin disposal.',
        parameters: [],
      },
      {
        signature: 'inject(key: keyof SlotMap & string, callback: () => SlotInjectionEffect): () => void',
        description: 'Install an effect for each declaration lifetime of a slot. The callback runs synchronously when the declaration already exists; otherwise it runs inside the declaring `register()` call after the declaration is committed. Collapse disposes the effect and a later declaration runs it again. Callback effects are synchronous disposers; iterable effects install transactionally and dispose in reverse order. The controller belongs to the caller\'s fiber, so plugin unload cancels a pending wait and removes any active contribution.',
        parameters: [{ name: 'key', description: 'declared SlotMap key to depend on.' }, { name: 'callback', description: 'creates one disposer or an iterable of disposers.' }],
        returns: 'idempotent disposer for the wait and active effect.',
        throws: ['callback setup failures synchronously when the slot is already declared.'],
      },
    ],
  },
  {
    key: 'theme',
    summary: 'Theme registry and preference owner.',
    description: 'Theme registry and preference owner. `light`/`dark` are built in (the base stylesheets carry both palettes); third-party themes register alias-layer overrides. Reads go through getTheme; preference writes only through setTheme; continuous sync only through the `theme/change` event. overrideTokens stacks partial token layers over the active theme without touching the registry. The service holds the `prefers-color-scheme` media query (environment sensing, not presentation) and re-emits when the OS scheme flips while the preference is `system`.',
    methods: [
      {
        signature: 'getTheme(): ThemeSnapshot',
        description: 'Read the current immutable theme snapshot.',
        parameters: [],
        returns: 'the current snapshot (stable reference until the next change).',
      },
      {
        signature: 'setTheme(id: string): void',
        description: 'Switch the theme preference — the only user preference write entry. Built-in preferences are written through the settings scope and every accepted value emits `theme/change`.',
        parameters: [{ name: 'id', description: 'a registered theme id or `system`; unknown ids throw.' }],
      },
      {
        signature: 'setFontSize(px: number): void',
        description: 'Change the conversation content font size — the only font-size write entry. Accepted values are written through the settings scope and emit `theme/change`.',
        parameters: [{ name: 'px', description: 'integer px within FONT_SIZE_MIN..FONT_SIZE_MAX; out-of-range or fractional values throw.' }],
      },
      {
        signature: 'register(definition: ThemeDefinition): () => void',
        description: 'Register a theme. Duplicate id throws (single occupant per id; the built-in pair counts; `system` is a preference, not a registrable id).',
        parameters: [{ name: 'definition', description: 'theme id, colorScheme, and alias-token overrides.' }],
        returns: 'disposer. Disposing the theme backing the active preference resets the preference to the default so the UI never keeps tokens of an unregistered theme.',
      },
      {
        signature: 'overrideTokens(source: string, tokens: ThemeTokenOverrides): () => void',
        description: 'Stack a token override layer on top of the active theme — the token-level analogue of slot shading: the base theme stays untouched, layers compose in seq order with later layers winning per-token, and removing a layer restores whatever it covered. Calling again with the same source replaces that source\'s whole layer and restacks it on top (effect re-registration semantics). Emits `theme/change` with the recomposed snapshot.',
        parameters: [{ name: 'source', description: 'layer identity; one layer per source (dynamic packages pass their package id — the façade pins it, so it also names the layer\'s origin for inspection).' }, { name: 'tokens', description: 'token-name → `{ light, dark }` value pairs. Validated at runtime (model-authored callers reach this boundary with untyped JS); a bare string value throws a teaching error.' }],
        returns: 'disposer removing exactly the layer this call created; a no-op once the source has re-overridden (the newer layer is not torn down).',
      },
    ],
  },
  {
    key: 'timer',
    summary: 'Disposable timer helpers mixed into Cordis contexts.',
    description: 'Disposable timer helpers mixed into Cordis contexts.',
    methods: [
      {
        signature: 'timeout(callback: () => void, delay: number): () => void',
        description: 'Run a callback once and return its disposer.',
        parameters: [],
      },
      {
        signature: 'timeout(delay: number): Promise<void>',
        description: 'Resolve after a delay; disposal rejects the pending promise.',
        parameters: [],
      },
      {
        signature: 'interval(callback: () => void, delay: number): () => void',
        description: 'Run a callback repeatedly and return its disposer.',
        parameters: [],
      },
      {
        signature: 'interval<R = any>(delay: number): AsyncIterableIterator<void, R, void>',
        description: 'Return an async iterator of timer ticks.',
        parameters: [],
      },
      {
        signature: 'throttle<F extends (...args: any[]) => void>(callback: F, delay: number, noTrailing?: boolean): F & { dispose: () => void }',
        description: 'Return a throttled function whose timer is disposed with the current fiber.',
        parameters: [],
      },
      {
        signature: 'debounce<F extends (...args: any[]) => void>(callback: F, delay: number): F & { dispose: () => void }',
        description: 'Return a debounced function whose timer is disposed with the current fiber.',
        parameters: [],
      },
    ],
  },
  {
    key: 'uiWorkspace',
    summary: 'Workspace archive and directory operations consumed by Client UI domains.',
    description: 'Workspace archive and directory operations consumed by Client UI domains.',
    methods: [
      {
        signature: 'openSession(sessionId: SessionId): void',
        description: 'Select a Session and show its Conversation as one UI navigation action.',
        parameters: [{ name: 'sessionId', description: 'listed or retained Session to display.' }],
      },
      {
        signature: 'openWorkspace(workspaceId: WorkspaceId, beforeOpen?: (sessionId: SessionId) => void): Promise<void>',
        description: 'Connect a Workspace and open its Session unless a later navigation supersedes it.',
        parameters: [{ name: 'workspaceId', description: 'target Workspace.' }, { name: 'beforeOpen', description: 'optional synchronous preparation for the selected Session, skipped after supersession.' }],
        returns: 'completion; a superseded request may create a Session but does not open it.',
      },
      {
        signature: 'forkSession(sessionId: SessionId): Promise<void>',
        description: 'Fork a Session and open the child unless a later navigation supersedes it.',
        parameters: [{ name: 'sessionId', description: 'source Session.' }],
        returns: 'completion; a superseded request leaves its child available without selecting it.',
      },
      {
        signature: 'connectWorkspace(workspaceId: WorkspaceId): Promise<SessionId>',
        description: 'Resolve the reusable or newly created blank Session for a Workspace.',
        parameters: [{ name: 'workspaceId', description: 'target Workspace.' }],
        returns: 'a Session already addressable through the Session Controller.',
      },
      {
        signature: 'startSession(workspaceId?: WorkspaceId): void',
        description: 'Start a New Session flow and navigate to its Session.',
        parameters: [{ name: 'workspaceId', description: 'explicit target; absent inherits the current or most recent Workspace.' }],
      },
      {
        signature: 'archiveSession(sessionId: SessionId): Promise<void>',
        description: 'Archive a Session and clear it when it is the current selection.',
        parameters: [{ name: 'sessionId', description: 'Session to archive.' }],
      },
      {
        signature: 'pickDirectory(): Promise<string | null>',
        description: 'Open the Host-native directory picker.',
        parameters: [],
        returns: 'the selected directory, or null when cancelled.',
      },
      {
        signature: 'listDirectory(path?: string, signal?: AbortSignal): Promise<DirectoryListing>',
        description: 'List one Host directory level.',
        parameters: [{ name: 'path', description: 'directory path; absent selects the Host home.' }, { name: 'signal', description: 'cancellation for a superseded scan.' }],
        returns: 'directory entries and breadcrumb ancestry.',
      },
      {
        signature: 'createDirectory(path: string, name: string): Promise<string>',
        description: 'Create a child directory.',
        parameters: [{ name: 'path', description: 'existing parent directory.' }, { name: 'name', description: 'child directory name.' }],
        returns: 'created absolute path.',
      },
    ],
  },
  {
    key: 'workspaces',
    summary: 'Workspace Controller\'s Client service face.',
    description: 'Workspace Controller\'s Client service face.',
    methods: [
      {
        signature: 'create(input: { path: string }): Promise<WorkspaceView>',
        description: 'Register an existing path as a Workspace.',
        parameters: [{ name: 'input', description: 'Host create payload.' }],
        returns: 'the created or idempotently resolved Workspace.',
      },
      {
        signature: 'rename(workspaceId: WorkspaceId, title: string): Promise<WorkspaceView>',
        description: 'Rename a Workspace.',
        parameters: [{ name: 'workspaceId', description: 'target Workspace.' }, { name: 'title', description: 'new display title.' }],
        returns: 'the renamed Workspace.',
      },
      {
        signature: 'delete(workspaceId: WorkspaceId): Promise<void>',
        description: 'Delete a Workspace registration without deleting Sessions or files.',
        parameters: [{ name: 'workspaceId', description: 'target Workspace.' }],
      },
      {
        signature: 'archiveSession(sessionId: SessionId): Promise<void>',
        description: 'Archive a Session from Workspace grouping surfaces.',
        parameters: [{ name: 'sessionId', description: 'Session to archive.' }],
      },
      {
        signature: 'insertSessionBefore( workspaceId: WorkspaceId, sessionId: SessionId, beforeSessionId?: SessionId, ): Promise<WorkspaceView>',
        description: 'Move a Session within one Workspace account.',
        parameters: [{ name: 'workspaceId', description: 'owning Workspace.' }, { name: 'sessionId', description: 'Session to move.' }, { name: 'beforeSessionId', description: 'anchor Session; omitted appends.' }],
        returns: 'the changed Workspace.',
      },
    ],
  },
]

/** Every harness event, sorted by name. */
export const EVENT_API: readonly EventApiEntry[] = [
  {
    name: 'connection/reset',
    mode: 'emit',
    signature: '\'connection/reset\'(): void',
    summary: 'A connection generation was established.',
    description: 'A connection generation was established. Wire-derived caches must repull; long-lived streams own their own resume and baseline lifecycle.',
    parameters: [],
  },
  {
    name: 'locale/change',
    mode: 'emit',
    signature: '\'locale/change\'(snapshot: LocaleSnapshot): void',
    summary: 'The active locale switched.',
    description: 'The active locale switched. Dictionary registrations do NOT emit this event (listeners may re-register slots in response, and boot registers one namespace per package); continuous render refresh rides the LocaleFace revision instead.',
    parameters: [{ name: 'snapshot', description: 'Current immutable locale snapshot.' }],
  },
  {
    name: 'slots/changed',
    mode: 'emit',
    signature: '\'slots/changed\'(key: string): void',
    summary: 'A slot declaration or registration set changed.',
    description: 'A slot declaration or registration set changed.',
    parameters: [{ name: 'key', description: 'mutated SlotMap key.' }],
  },
  {
    name: 'theme/change',
    mode: 'emit',
    signature: '\'theme/change\'(snapshot: ThemeSnapshot): void',
    summary: 'Theme state changed (preference switched, registry updated, or the OS color scheme changed while the preference is `system`).',
    description: 'Theme state changed (preference switched, registry updated, or the OS color scheme changed while the preference is `system`).',
    parameters: [{ name: 'snapshot', description: 'Current immutable theme snapshot.' }],
  },
]

/** Shapes of every exported type the Service and Event signatures reference (transitively), sorted by name. */
export const TYPE_API: readonly TypeApiEntry[] = [
  {
    name: 'ActionsDecl',
    declaration: 'export type ActionsDecl<T> = Record<string, (draft: T, ...params: any[]) => void>;',
  },
  {
    name: 'AgentContext',
    declaration: 'export type AgentContext = Omit<Context, \'remote\'> & {\n    readonly remote: ClientRemote & TypertRemoteScopeApi<\'agent\'>;\n};',
  },
  {
    name: 'AssistantLiveChunkEvent',
    declaration: 'export interface AssistantLiveChunkEvent {\n    readonly type: \'assistant/live-chunk\';\n    readonly seq: number;\n    readonly time: number;\n    readonly data: {\n        readonly attemptId: LlmAttemptId;\n        readonly turn: number;\n        readonly step: number;\n        readonly chunk: StreamChunk;\n    };\n}',
  },
  {
    name: 'BakedActions',
    declaration: 'export type BakedActions<T, A extends ActionsDecl<T>> = {\n    [K in keyof A]: A[K] extends (draft: T, ...params: infer P) => void ? (...params: P) => void : never;\n};',
  },
  {
    name: 'BeginSubmissionInput',
    declaration: 'export interface BeginSubmissionInput {\n    readonly mode: \'queue\' | \'steer\';\n    readonly text: string;\n    readonly attachments: readonly PendingSubmissionAttachment[];\n    readonly onRetire?: (retirement: PendingSubmissionRetirement) => void;\n}',
  },
  {
    name: 'BoundActions',
    declaration: 'export type BoundActions<H> = H extends StoreHandle<infer T, infer A> ? BakedActions<T, A> : never;',
  },
  {
    name: 'BuiltInLocaleId',
    declaration: 'export type BuiltInLocaleId = typeof LOCALE_IDS[number];',
  },
  {
    name: 'ChainKeysOf',
    declaration: 'export type ChainKeysOf<S extends keyof SlotMap & string> = S extends unknown ? (SlotMap[S][\'kind\'] extends \'chain\' ? S : never) : never;',
  },
  {
    name: 'ChainRenderOpts',
    declaration: 'export interface ChainRenderOpts {\n    fallback?: ReactNode;\n    fallbackOnly?: boolean;\n    overlay?: boolean;\n}',
  },
  {
    name: 'ChildrenDecl',
    declaration: 'export type ChildrenDecl = {\n    [P in keyof SlotMap & string]?: SlotSpec<SlotMap[P]>;\n};',
  },
  {
    name: 'ClientConnectionRpc',
    declaration: 'export interface ClientConnectionRpc {\n    call(channel: string, endpoint: string, payload: unknown, signal?: AbortSignal): Promise<ConnectionRpcResult<unknown>>;\n    readonly open?: (channel: string, endpoint: string, payload: unknown, signal: AbortSignal) => AsyncIterable<unknown>;\n}',
  },
  {
    name: 'ClientRemote',
    declaration: 'export interface ClientRemote extends TypertClientRemote {\n    $stream<Item>(options: RemoteStreamOptions<Item>): RemoteStream<Item>;\n    readonly $host: RemoteHostFacts;\n}',
  },
  {
    name: 'CommonKeyOf',
    declaration: 'export type CommonKeyOf = LocaleNamespaceMap extends {\n    common: infer C;\n} ? C & string : never;',
  },
  {
    name: 'ComposedProps',
    declaration: 'export type ComposedProps<K extends keyof SlotMap & string, EntryKey extends EntryKeyOf<K>, S extends keyof SlotMap & string, H, I extends object, M = never, N = undefined> = PropsRuntime<K, EntryKey> & PropsRenderSlots<S> & PropsStore<H> & InjectFace<I> & MatchedShare<SlotMap[K], M> & PropsLocale<N>;',
  },
  {
    name: 'ConnectionGeneration',
    declaration: 'export interface ConnectionGeneration {\n    readonly id: number;\n    readonly host: ConnectionHostInfo;\n}',
  },
  {
    name: 'ConnectionGenerationSource',
    declaration: 'export type ConnectionGenerationSource = (signal: AbortSignal, ready: (host: ConnectionHostInfo) => void) => Promise<void>;',
  },
  {
    name: 'ConnectionGenerationState',
    declaration: 'export interface ConnectionGenerationState {\n    getSnapshot(): ConnectionGeneration | undefined;\n    subscribe(listener: () => void): () => void;\n}',
  },
  {
    name: 'ConnectionHandle',
    declaration: 'export interface ConnectionHandle {\n    readonly isLoopback: boolean;\n    readonly generation: ConnectionGenerationState;\n    readonly state: ConnectionStateSource;\n    readonly rpc: ClientConnectionRpc;\n    reconnect(): void;\n    registerGenerationSource(source: ConnectionGenerationSource): () => void;\n    start(sinks: ConnectionSinks, config?: ConnectionRecoveryConfig): ConnectionLoop;\n}',
  },
  {
    name: 'ConnectionHostInfo',
    declaration: 'export interface ConnectionHostInfo {\n    readonly home: string;\n}',
  },
  {
    name: 'ConnectionLoop',
    declaration: 'export interface ConnectionLoop {\n    stop(): void;\n}',
  },
  {
    name: 'ConnectionRecoveryConfig',
    declaration: 'export interface ConnectionRecoveryConfig {\n    backoffBaseMs?: number;\n    backoffFactor?: number;\n    backoffMaxMs?: number;\n    generationReadyWarnMs?: number;\n    generationReadyTimeoutMs?: number;\n}',
  },
  {
    name: 'ConnectionRpcFailure',
    declaration: 'export interface ConnectionRpcFailure {\n    readonly code: string;\n    readonly message: string;\n    readonly details: object;\n}',
  },
  {
    name: 'ConnectionRpcResult',
    declaration: 'export type ConnectionRpcResult<T> = {\n    readonly ok: true;\n    readonly value: T;\n} | {\n    readonly ok: false;\n    readonly error: ConnectionRpcFailure;\n};',
  },
  {
    name: 'ConnectionSinks',
    declaration: 'export interface ConnectionSinks {\n    onConnected?: (host: ConnectionHostInfo) => void;\n    onStateChange?: (state: ConnectionState) => void;\n    onReconnectRequested?: () => void;\n}',
  },
  {
    name: 'ConnectionState',
    declaration: 'export type ConnectionState = \'connected\' | \'disconnected\' | \'connecting\';',
  },
  {
    name: 'ConnectionStateSource',
    declaration: 'export interface ConnectionStateSource {\n    getSnapshot(): ConnectionState | undefined;\n    subscribe(listener: () => void): () => void;\n}',
  },
  {
    name: 'EntryKeyOf',
    declaration: 'export type EntryKeyOf<K extends keyof SlotMap & string> = SlotMap[K] extends {\n    kind: \'keyed\';\n    keyProps: infer P extends object;\n} ? keyof P & string : string;',
  },
  {
    name: 'GlobalStandardProps',
    declaration: 'export interface GlobalStandardProps {\n}',
  },
  {
    name: 'HandleOf',
    declaration: 'export type HandleOf<H> = H extends () => infer R ? R : H;',
  },
  {
    name: 'HooksSources',
    declaration: 'export type HooksSources = Record<string, HostObservable<unknown>>;',
  },
  {
    name: 'HostObservable',
    declaration: 'export type HostObservable<T> = ObservableSnapshot<T>;',
  },
  {
    name: 'InjectFace',
    declaration: 'export type InjectFace<I extends object> = I extends {\n    hooks: infer HS extends HooksSources;\n} ? I extends {\n    keyedHooks: infer KS extends KeyedHooksSources;\n} ? Omit<I, \'hooks\' | \'keyedHooks\'> & PropsHooks<HS> & PropsKeyedHooks<KS> : Omit<I, \'hooks\'> & PropsHooks<HS> : I extends {\n    keyedHooks: infer KS extends KeyedHooksSources;\n} ? Omit<I, \'keyedHooks\'> & PropsKeyedHooks<KS> : I;',
  },
  {
    name: 'InjectParams',
    declaration: 'export type InjectParams<K extends keyof SlotMap & string, H> = ScopeOf<K> extends \'session\' ? ([\n    H\n] extends [\n    StoreDecl\n] ? [\n    sessionId: SessionIdOf,\n    actions: BoundActions<HandleOf<H>>\n] : [\n    sessionId: SessionIdOf\n]) : ScopeOf<K> extends \'session-maybe\' ? ([\n    H\n] extends [\n    StoreDecl\n] ? [\n    sessionId: SessionIdOf | undefined,\n    actions: BoundActions<HandleOf<H>> | undefined\n] : [\n    sessionId: SessionIdOf | undefined\n]) : ([\n    H\n] extends [\n    StoreDecl\n] ? [\n    actions: BoundActions<HandleOf<H>>\n] : [\n]);',
  },
  {
    name: 'ISession',
    declaration: 'export interface ISession {\n    readonly sessionId: SessionId;\n    readonly projections: ProjectionsFace;\n    beginSubmission(input: BeginSubmissionInput): SubmissionHandle;\n    prompt(content: PromptContentPart[], mode: \'queue\' | \'steer\', signal?: AbortSignal, requestId?: SessionRequestId): Promise<RemoteResult<{\n        accepted: true;\n    }>>;\n    readAttachment(attachmentId: AttachmentIdType): Promise<RemoteResult<{\n        attachment: ImageAttachmentRef;\n        data: Uint8Array;\n    }>>;\n    updateQueue(itemId: MessageId, action: QueueAction): Promise<RemoteResult<{\n        accepted: true;\n    }>>;\n    cancel(): Promise<RemoteResult<{\n        accepted: true;\n    }>>;\n    rename(title: string): Promise<RemoteResult<{\n        title: string;\n        seq: SessionSeq;\n    }>>;\n    loadOlder(): Promise<void>;\n    loadThrough(seq: SessionSeq): Promise<void>;\n    deleteFrom(fromSeq: SessionSeq): Promise<RemoteResult<{\n        accepted: true;\n    }>>;\n    resync(): Promise<void>;\n    command(line: string): Promise<RemoteResult<{\n        matched: boolean;\n    }>>;\n}',
  },
  {
    name: 'KeyedHooksSources',
    declaration: 'export type KeyedHooksSources = Record<string, KeyedStandardSource>;',
  },
  {
    name: 'KeyedSnapshotSelectorHook',
    declaration: 'export type KeyedSnapshotSelectorHook<Snapshot> = {\n    (key: string): Snapshot | undefined;\n    <Selected>(key: string, selector: (value: Snapshot | undefined) => Selected, equal?: (left: Selected, right: Selected) => boolean): Selected;\n};',
  },
  {
    name: 'KeyedStandardSource',
    declaration: 'export type KeyedStandardSource = (key: string) => HostObservable<unknown> | undefined;',
  },
  {
    name: 'KeyPropsOf',
    declaration: 'export type KeyPropsOf<K extends keyof SlotMap & string, EntryKey extends EntryKeyOf<K>> = SlotMap[K] extends {\n    kind: \'keyed\';\n    keyProps: infer P extends object;\n} ? EntryKey extends keyof P ? P[EntryKey] extends object ? P[EntryKey] : never : never : object;',
  },
  {
    name: 'LanguageRegistration',
    declaration: 'export interface LanguageRegistration {\n    id: LocaleId;\n    label: string;\n    fallback: LocaleId;\n}',
  },
  {
    name: 'LocaleDefinition',
    declaration: 'export interface LocaleDefinition {\n    readonly id: LocaleId;\n    readonly label: string;\n    readonly fallback?: LocaleId;\n}',
  },
  {
    name: 'LocaleDict',
    declaration: 'export type LocaleDict = Record<string, string>;',
  },
  {
    name: 'LocaleDictOf',
    declaration: 'export type LocaleDictOf<N extends keyof LocaleNamespaceMap & string> = Record<LocaleNamespaceMap[N] & string, string>;',
  },
  {
    name: 'LocaleId',
    declaration: 'export type LocaleId = string;',
  },
  {
    name: 'LocaleKeysOf',
    declaration: 'export type LocaleKeysOf<N extends keyof LocaleNamespaceMap & string> = (LocaleNamespaceMap[N] & string) | CommonKeyOf;',
  },
  {
    name: 'LocaleNamespaceMap',
    declaration: 'export interface LocaleNamespaceMap {\n}',
  },
  {
    name: 'LocaleSnapshot',
    declaration: 'export interface LocaleSnapshot {\n    active: LocaleId;\n    locales: readonly LocaleDefinition[];\n    revision: number;\n}',
  },
  {
    name: 'MainPanelId',
    declaration: 'export type MainPanelId = Branded<\'MainPanelId\'>;',
  },
  {
    name: 'MatchedShare',
    declaration: 'export type MatchedShare<E extends SlotEntryDef, M> = E[\'kind\'] extends \'chain\' ? {\n    matched: M;\n} : object;',
  },
  {
    name: 'ObservableSnapshot',
    declaration: 'export interface ObservableSnapshot<T> {\n    getSnapshot(): T;\n    subscribe(fn: () => void): () => void;\n}',
  },
  {
    name: 'OpenState',
    declaration: 'export type OpenState = \'cold\' | \'loading\' | \'open\' | \'error\';',
  },
  {
    name: 'OwnerOf',
    declaration: 'export type OwnerOf<K extends keyof SlotMap & string> = SlotMap[K] extends {\n    owner: infer O extends object;\n} ? O : object;',
  },
  {
    name: 'PendingSubmission',
    declaration: 'export interface PendingSubmission {\n    readonly requestId: SessionRequestId;\n    readonly placement: PendingSubmissionPlacement;\n    readonly time: number;\n    readonly text: string;\n    readonly attachments: readonly PendingSubmissionAttachment[];\n}',
  },
  {
    name: 'PendingSubmissionAttachment',
    declaration: 'export type PendingSubmissionAttachment = PendingSubmissionImageAttachment | PendingSubmissionFileAttachment;',
  },
  {
    name: 'PendingSubmissionFileAttachment',
    declaration: 'export interface PendingSubmissionFileAttachment {\n    readonly type: \'file\';\n    readonly value: FileAttachmentRef;\n}',
  },
  {
    name: 'PendingSubmissionImage',
    declaration: 'export interface PendingSubmissionImage {\n    readonly previewUrl: string;\n    readonly name?: string;\n    readonly width?: number;\n    readonly height?: number;\n}',
  },
  {
    name: 'PendingSubmissionImageAttachment',
    declaration: 'export interface PendingSubmissionImageAttachment {\n    readonly type: \'image\';\n    readonly value: PendingSubmissionImage;\n}',
  },
  {
    name: 'PendingSubmissionPlacement',
    declaration: 'export type PendingSubmissionPlacement = \'transcript\' | \'queued\' | \'steering\';',
  },
  {
    name: 'PendingSubmissionRetirement',
    declaration: 'export type PendingSubmissionRetirement = {\n    readonly reason: \'observed\';\n    readonly attachments: readonly (ImageAttachmentRef | FileAttachmentRef)[];\n} | {\n    readonly reason: \'failed\';\n};',
  },
  {
    name: 'ProjectionsFace',
    declaration: 'export interface ProjectionsFace {\n    faceOf(key: string): ObservableSnapshot<unknown>;\n}',
  },
  {
    name: 'PromptContentPart',
    declaration: 'export type PromptContentPart = {\n    readonly type: \'text\';\n    readonly text: string;\n} | {\n    readonly type: \'image\';\n    readonly mediaType: ImageMediaType;\n    readonly data: string;\n    readonly name?: string;\n} | {\n    readonly type: \'file\';\n    readonly receiptId: Branded<\'file-upload-receipt-id\'>;\n};',
  },
  {
    name: 'PromptError',
    declaration: 'export interface PromptError {\n    readonly op: \'send\' | \'stop\';\n    readonly error: RemoteFailure;\n}',
  },
  {
    name: 'PropsHooks',
    declaration: 'export type PropsHooks<HS extends HooksSources> = {\n    [N in keyof HS & string as `use${Capitalize<N>}`]: SnapshotSelectorHook<HS[N] extends HostObservable<infer T> ? T : never>;\n};',
  },
  {
    name: 'PropsKeyedHooks',
    declaration: 'export type PropsKeyedHooks<HS extends KeyedHooksSources> = {\n    [N in keyof HS & string as `use${Capitalize<N>}`]: KeyedSnapshotSelectorHook<HS[N] extends (key: string) => HostObservable<infer T> | undefined ? T : never>;\n};',
  },
  {
    name: 'PropsLocale',
    declaration: 'export type PropsLocale<N> = N extends keyof LocaleNamespaceMap & string ? {\n    t: TranslateNS<N>;\n} : object;',
  },
  {
    name: 'PropsRenderSlots',
    declaration: 'export type PropsRenderSlots<S extends keyof SlotMap & string> = {\n    renderSlot: RenderSlotFn<Exclude<S, ChainKeysOf<S>>>;\n    readonly __renders?: ((key: S) => void) | undefined;\n} & ([\n    ChainKeysOf<S>\n] extends [\n    never\n] ? object : {\n    renderSlotChain: <K extends ChainKeysOf<S>>(key: K, owner: OwnerOf<K>, opts?: ChainRenderOpts) => ReactNode;\n}) & (\'session\' extends ScopeOf<S> ? {\n    SessionProvider: SessionProviderComponent;\n} : object);',
  },
  {
    name: 'PropsRuntime',
    declaration: 'export type PropsRuntime<K extends keyof SlotMap & string, EntryKey extends EntryKeyOf<K> = EntryKeyOf<K>> = OwnerOf<K> & KeyPropsOf<K, EntryKey> & SlotInjectFace<SlotInjectOf<K>> & (ScopeOf<K> extends \'session\' ? SessionStandardProps : ScopeOf<K> extends \'session-maybe\' ? SessionMaybeStandardProps : object) & GlobalStandardProps;',
  },
  {
    name: 'PropsSlotHooks',
    declaration: 'export type PropsSlotHooks<HS extends object> = {\n    [N in keyof HS & string as `use${Capitalize<N>}`]: BoundHookOf<HS[N]>;\n};',
  },
  {
    name: 'PropsStore',
    declaration: 'export type PropsStore<H> = H extends StoreHandle<infer T, infer A> ? {\n    useStore: SnapshotSelectorHook<T>;\n    actions: BakedActions<T, A>;\n} : object;',
  },
  {
    name: 'RemoteHostFacts',
    declaration: 'export interface RemoteHostFacts {\n    readonly home: string | undefined;\n    readonly isLoopback: boolean;\n}',
  },
  {
    name: 'RemoteStream',
    declaration: 'export class RemoteStream<Item> implements AsyncIterable<RemoteStreamItem<Item>> {\n    constructor(private readonly connection: Pick<ConnectionHandle, \'generation\'>, private readonly options: RemoteStreamOptions<Item>);\n    get signal(): AbortSignal;\n    restart(): void;\n    dispose(): Promise<void>;\n    [Symbol.asyncIterator](): AsyncIterator<RemoteStreamItem<Item>>;\n}',
  },
  {
    name: 'RemoteStreamCarrierError',
    declaration: 'export class RemoteStreamCarrierError extends Error {\n    constructor(message: string, options?: ErrorOptions);\n}',
  },
  {
    name: 'RemoteStreamItem',
    declaration: 'export interface RemoteStreamItem<Item> {\n    readonly generation: number;\n    readonly value: Item;\n    readonly signal: AbortSignal;\n    accept(): void;\n}',
  },
  {
    name: 'RemoteStreamOptions',
    declaration: 'export interface RemoteStreamOptions<Item> {\n    readonly name: string;\n    readonly open: (signal: AbortSignal) => AsyncIterable<Item>;\n    readonly ended: (accepted: boolean) => Error;\n    readonly carrierFailed?: (error: RemoteStreamCarrierError) => void;\n}',
  },
  {
    name: 'ScopeOf',
    declaration: 'export type ScopeOf<K extends keyof SlotMap & string> = SlotMap[K][\'scope\'];',
  },
  {
    name: 'SessionAreaProps',
    declaration: 'export interface SessionAreaProps {\n    empty?: (() => ReactNode) | undefined;\n    children: ReactNode;\n}',
  },
  {
    name: 'SessionAssistantSettlementEntry',
    declaration: 'export interface SessionAssistantSettlementEntry {\n    readonly type: \'event\';\n    readonly event: SessionEvent<\'assistant/message\'> | SessionEvent<\'assistant/attempt\'>;\n}',
  },
  {
    name: 'SessionBinding',
    declaration: 'export interface SessionBinding {\n    readonly sessionId: SessionId;\n    readonly session: SessionFace;\n    readonly eventSource: SessionEventSource;\n    readonly ctx: AgentContext;\n}',
  },
  {
    name: 'SessionEventChange',
    declaration: 'export type SessionEventChange = {\n    readonly kind: \'replace\';\n    readonly entries: readonly SessionEventLikeEntry[];\n} | {\n    readonly kind: \'prepend\';\n    readonly entries: readonly SessionEventLikeEntry[];\n} | {\n    readonly kind: \'append\';\n    readonly entries: readonly SessionEventLikeEntry[];\n} | {\n    readonly kind: \'settle-assistant\';\n    readonly attemptId: LlmAttemptId;\n    readonly entry?: SessionAssistantSettlementEntry;\n};',
  },
  {
    name: 'SessionEventLikeEntry',
    declaration: 'export type SessionEventLikeEntry = {\n    readonly type: \'event\';\n    readonly event: SessionEvent;\n} | {\n    readonly type: \'transient\';\n    readonly event: AssistantLiveChunkEvent;\n};',
  },
  {
    name: 'SessionEventSource',
    declaration: 'export type SessionEventSource = ObservableSnapshot<SessionEventWindow>;',
  },
  {
    name: 'SessionEventWindow',
    declaration: 'export interface SessionEventWindow {\n    readonly entries: readonly SessionEventLikeEntry[];\n    readonly hasMore: boolean;\n    readonly revision: number;\n    readonly change: SessionEventChange;\n}',
  },
  {
    name: 'SessionFace',
    declaration: 'export type SessionFace = ISession & ObservableSnapshot<SessionSnapshot>;',
  },
  {
    name: 'SessionIdOf',
    declaration: 'export type SessionIdOf = SessionStandardProps extends {\n    sessionId: infer S;\n} ? S : string;',
  },
  {
    name: 'SessionMaybeStandardProps',
    declaration: 'export interface SessionMaybeStandardProps {\n}',
  },
  {
    name: 'SessionProviderComponent',
    declaration: 'export type SessionProviderComponent = (props: SessionAreaProps) => ReactNode;',
  },
  {
    name: 'SessionRequestId',
    declaration: 'export type SessionRequestId = Branded<\'session-request-id\'>;',
  },
  {
    name: 'SessionSearchResultItem',
    declaration: 'export interface SessionSearchResultItem {\n    sessionId: SessionId;\n    snippet: string;\n}',
  },
  {
    name: 'SessionSnapshot',
    declaration: 'export interface SessionSnapshot {\n    readonly sessionId: SessionId;\n    readonly queue: readonly QueuedMessage[];\n    readonly pendingSubmissions: readonly PendingSubmission[];\n    readonly running: boolean;\n    readonly subagent: {\n        readonly address: SubagentAddress;\n        readonly parentAvailable?: boolean;\n    } | null;\n    readonly removed: boolean;\n    readonly openState: OpenState;\n    readonly openError: RemoteFailure | null;\n    readonly hasMore: boolean;\n    readonly loadingOlder: boolean;\n    readonly promptError: PromptError | null;\n    readonly blank: boolean;\n    readonly lastAgentError: string | null;\n    readonly promptAttempted: boolean;\n    readonly awaitingFirstTurn: boolean;\n}',
  },
  {
    name: 'SessionStandardProps',
    declaration: 'export interface SessionStandardProps {\n}',
  },
  {
    name: 'SlotComponent',
    declaration: 'export type SlotComponent<P> = (props: P) => ReactNode;',
  },
  {
    name: 'SlotCore',
    declaration: 'export class SlotCore {\n    constructor();\n    register<K extends keyof SlotMap & string, const EntryKey extends EntryKeyOf<K> = EntryKeyOf<K>, const D extends ChildrenDecl = Record<never, never>, H extends StoreDecl | undefined = undefined, M = never, N extends (keyof LocaleNamespaceMap & string) | undefined = undefined, C extends SlotComponent<never> = SlotComponent<never>>(options: BaseOptions<K, EntryKey, D, H, M, N> & {\n        inject?: undefined;\n    }, component: C & SlotComponent<ComposedProps<K, NoInfer<EntryKey>, keyof NoInfer<D> & keyof SlotMap & string, HandleOf<NoInfer<H>>, object, NoInfer<M>, NoInfer<N>>> & RendersCheck<C, D>): () => void;\n    register<K extends keyof SlotMap & string, I extends object, const EntryKey extends EntryKeyOf<K> = EntryKeyOf<K>, const D extends ChildrenDecl = Record<never, never>, H extends StoreDecl | undefined = undefined, M = never, N extends (keyof LocaleNamespaceMap & string) | undefined = undefined, C extends SlotComponent<never> = SlotComponent<never>>(options: BaseOptions<K, EntryKey, D, H, M, N> & {\n        inject: (...args: InjectParams<K, H>) => I;\n    }, component: C & SlotComponent<ComposedProps<K, NoInfer<EntryKey>, keyof NoInfer<D> & keyof SlotMap & string, HandleOf<NoInfer<H>>, I, NoInfer<M>, NoInfer<N>>> & RendersCheck<C, D>): () => void;\n    register(options: ErasedOptions, component: unknown): () => void;\n    isLive(entry: StoredEntry): boolean;\n    entries(key: string): readonly StoredEntry[];\n    entriesOfSlot(key /* …truncated — full shape in source */',
  },
  {
    name: 'SlotEntryDef',
    declaration: 'export interface SlotEntryDef {\n    kind: SlotKind;\n    scope: SlotScope;\n    owner?: object;\n    keyProps?: Record<string, object>;\n    hookContext?: unknown;\n    inject?: object;\n}',
  },
  {
    name: 'SlotInjectFace',
    declaration: 'export type SlotInjectFace<I extends object> = I extends {\n    hooks: infer HS extends object;\n} ? Omit<I, \'hooks\'> & PropsSlotHooks<HS> : I;',
  },
  {
    name: 'SlotInjectOf',
    declaration: 'export type SlotInjectOf<K extends keyof SlotMap & string> = SlotMap[K] extends {\n    inject: infer Injected extends object;\n} ? Injected : object;',
  },
  {
    name: 'SlotKind',
    declaration: 'export type SlotKind = \'single\' | \'list\' | \'keyed\' | \'chain\';',
  },
  {
    name: 'SlotLabel',
    declaration: 'export type SlotLabel = string | (() => string);',
  },
  {
    name: 'SlotMap',
    declaration: 'export interface SlotMap {\n}',
  },
  {
    name: 'SlotScope',
    declaration: 'export type SlotScope = \'root\' | \'session-maybe\' | \'session\';',
  },
  {
    name: 'SlotSpec',
    declaration: 'export type SlotSpec<E extends SlotEntryDef> = {\n    kind: E[\'kind\'];\n    scope: E[\'scope\'];\n} & (\'inject\' extends keyof E ? E extends {\n    inject: infer Injected extends object;\n} ? {\n    inject: Injected;\n} : {\n    inject?: object;\n} : {\n    inject?: never;\n});',
  },
  {
    name: 'SnapshotSelectorHook',
    declaration: 'export type SnapshotSelectorHook<T> = <S>(sel: (s: T) => S, eq?: (a: S, b: S) => boolean) => S;',
  },
  {
    name: 'StoreDecl',
    declaration: 'export type StoreDecl = StoreHandle<any, any> | StoreFactory;',
  },
  {
    name: 'StoredEntry',
    declaration: 'export interface StoredEntry {\n    component: unknown;\n    options: {\n        key?: string;\n        id?: string;\n        order?: number;\n        label?: SlotLabel;\n        priority?: number;\n    };\n    select?: ((owner: never) => unknown) | undefined;\n    inject?: ((...args: never[]) => Record<string, unknown>) | undefined;\n    children?: Readonly<Record<string, SlotSpec<SlotEntryDef>>> | undefined;\n    store?: StoreDecl | undefined;\n    locale?: string | undefined;\n    registrant?: string | undefined;\n}',
  },
  {
    name: 'StoreFactory',
    declaration: 'export type StoreFactory = () => StoreHandle<any, any>;',
  },
  {
    name: 'StoreHandle',
    declaration: 'export interface StoreHandle<T, A extends ActionsDecl<T>> {\n    readonly spec: StoreSpec<T, A>;\n    create(scopeKey?: string): StoreInstance<T, A>;\n}',
  },
  {
    name: 'StoreInstance',
    declaration: 'export interface StoreInstance<T, A extends ActionsDecl<T>> {\n    readonly actions: BakedActions<T, A>;\n    getSnapshot(): T;\n    subscribe(fn: () => void): () => void;\n    clearPersisted(): void;\n}',
  },
  {
    name: 'StoreSpec',
    declaration: 'export interface StoreSpec<T, A extends ActionsDecl<T>> {\n    init: () => T;\n    persist?: string;\n    actions: A;\n}',
  },
  {
    name: 'SubmissionHandle',
    declaration: 'export interface SubmissionHandle {\n    readonly requestId: SessionRequestId;\n    abandon(): void;\n}',
  },
  {
    name: 'ThemeDefinition',
    declaration: 'export interface ThemeDefinition {\n    id: string;\n    colorScheme: \'light\' | \'dark\';\n    tokens: ThemeTokens;\n}',
  },
  {
    name: 'ThemePreference',
    declaration: 'export type ThemePreference = typeof THEME_PREFERENCES[number];',
  },
  {
    name: 'ThemeSnapshot',
    declaration: 'export interface ThemeSnapshot {\n    preference: ThemePreference;\n    fontSize: number;\n    active: ThemeDefinition;\n    themes: readonly ThemeDefinition[];\n    revision: number;\n}',
  },
  {
    name: 'ThemeTokenModes',
    declaration: 'export interface ThemeTokenModes {\n    light: string;\n    dark: string;\n}',
  },
  {
    name: 'ThemeTokenOverrides',
    declaration: 'export type ThemeTokenOverrides = Record<string, ThemeTokenModes>;',
  },
  {
    name: 'ThemeTokens',
    declaration: 'export type ThemeTokens = Record<string, string>;',
  },
  {
    name: 'Translate',
    declaration: 'export type Translate<K extends string = string> = (key: K, params?: Record<string, unknown>) => string;',
  },
  {
    name: 'TranslateNS',
    declaration: 'export type TranslateNS<N extends keyof LocaleNamespaceMap & string> = Translate<LocaleKeysOf<N>>;',
  },
  {
    name: 'WorkspaceView',
    declaration: 'export interface WorkspaceView {\n    readonly workspaceId: WorkspaceId;\n    readonly path: string;\n    readonly title: string;\n    readonly sessionIds: readonly SessionId[];\n    readonly createdAt: string;\n    readonly updatedAt: string;\n}',
  },
]

/** The inherited `ctx` API (cordis core + loader/hmr/timer), in curated order. */
export const INHERITED_CTX_API: readonly InheritedApiEntry[] = [
  { name: 'ctx.on / ctx.once', summary: 'Register an event listener (disposable).' },
  { name: 'ctx.emit / ctx.parallel / ctx.serial / ctx.bail / ctx.waterfall', summary: 'Dispatch an event (sync / awaited / first-bail / short-circuit chain).' },
  { name: 'ctx.plugin / ctx.inject', summary: 'Load a plugin / declare required services.' },
  { name: 'ctx.effect', summary: 'Register a disposable side effect tied to the fiber.' },
  { name: 'ctx.get / ctx.set / ctx.provide / ctx.accessor / ctx.mixin', summary: 'Low-level service-store access and binding.' },
  { name: 'ctx.extend / ctx.isolate / ctx.intercept', summary: 'Derive a child context (scoped services / isolation / interception).' },
  { name: 'ctx.root / ctx.fiber / ctx.registry / ctx.reflect / ctx.events / ctx.logger', summary: 'Ambient handles onto the running context graph.' },
  { name: 'ctx.timer (+ interval / timeout / throttle / debounce)', summary: 'Disposable timer helpers. The `timer` key is provided at runtime; the four supported helpers are mixed onto ctx directly (declared via Pick).' },
  { name: 'ctx.loader', summary: 'The config Loader that booted the app (present under the loader).' },
  { name: 'ctx.hmr', summary: 'The hot-module-reload watcher (present under the hmr plugin).' },
]

function referencedTypeClosure(seeds: readonly string[]): TypeApiEntry[] {
  const included = new Set<string>()
  let frontier = [...seeds]
  while (frontier.length > 0) {
    const next: string[] = []
    for (const entry of TYPE_API) {
      if (included.has(entry.name)) continue
      const pattern = new RegExp(`\\b${entry.name}\\b`)
      if (!frontier.some(text => pattern.test(text))) continue
      included.add(entry.name)
      next.push(entry.declaration)
    }
    frontier = next
  }
  return TYPE_API.filter(entry => included.has(entry.name))
}

function contextProperty(key: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(key) ? `ctx.${key}` : `ctx[${JSON.stringify(key)}]`
}

/**
 * Project the Service Catalog as a compact directory or one exact coding contract.
 * @param key - exact Service key; omit it to list all Services and method signatures.
 * @param services - platform-specific visible Service entries.
 * @returns compact navigation data or one detailed Service with its referenced type closure.
 */
export function queryServiceApi(key?: string, services: readonly ServiceApiEntry[] = SERVICE_API): object {
  if (key === undefined) {
    return {
      mode: 'catalog',
      services: services.map(service => ({
        key: service.key,
        description: service.summary,
        methods: service.methods.map(method => ({ signature: method.signature })),
      })),
    }
  }
  const service = services.find(candidate => candidate.key === key)
  if (service === undefined) throw new Error(`no catalogued Service named "${key}"`)
  return {
    mode: 'service',
    service: {
      key: service.key,
      description: service.description,
      access: {
        optional: { expression: `ctx.get(${JSON.stringify(service.key)})`, requiresUndefinedCheck: true },
        hardDependency: { inject: [service.key], expression: contextProperty(service.key) },
      },
      methods: service.methods,
    },
    referencedTypes: referencedTypeClosure(service.methods.map(method => method.signature)),
  }
}

/**
 * Project the Event Catalog as a compact directory or one exact listener contract.
 * @param name - exact Event name; omit it to list all Events and listener signatures.
 * @param events - platform-specific visible Event entries.
 * @returns compact navigation data or one detailed Event with its referenced type closure.
 */
export function queryEventApi(name?: string, events: readonly EventApiEntry[] = EVENT_API): object {
  if (name === undefined) {
    return {
      mode: 'catalog',
      events: events.map(event => ({
        name: event.name,
        description: event.summary,
        mode: event.mode,
        signature: event.signature,
      })),
    }
  }
  const event = events.find(candidate => candidate.name === name)
  if (event === undefined) throw new Error(`no catalogued Event named "${name}"`)
  return {
    mode: 'event',
    event: {
      name: event.name,
      description: event.description,
      mode: event.mode,
      signature: event.signature,
      parameters: event.parameters,
    },
    referencedTypes: referencedTypeClosure([event.signature]),
  }
}
/* jscpd:ignore-end */
